version: '3'

services:
  orders-db:
    container_name: users_database
    image: postgres:16.3
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
